import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/UI/Nav";
import Footer from "@/components/UI/Footer";
import { Roboto } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader';
const roboto = Roboto({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Government College of Engineering, Jalgaon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
        color="red"
        initialPosition={0.08}
        showSpinner={false}
        height={4}
        />
        <Nav />
        <main className={`px-5 lg:px-20 pt-20 custom-scrollbar ${roboto.className}`}>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
